### ISSUE TITLE
一个小的讨论, 关于使用 class component 实现, 以及关于副作用和事件触发请求接口的方式

### ISSUE THREAD

**Issue by hacker0limbo** [acfasj/antd-table-crud#1]
首先感谢作者整理这么清晰详细的文章. 

我自己用 antd3 (class component) 和 antd4+ 都实现过类似中台表格页面. 其中 antd4+ 实现的思路和作者差不多. 本质核心还是监听 `query` 来进行后端请求的发送. 因为 query 一般包含两部分: 
- pagination, filter, sort 参数
- 表单参数(搜索条件等)

我看文章结尾略微提了一下用 class 组件实现的方法. 我个人有一些别的思路. 如果你参考 antd3 的官网 [远程加载数据](https://3x.ant.design/components/table-cn/#components-table-demo-ajax) 这块的 demo. 会发现其实请求数据这块的触发都是通过事件来进行的. 大概会有这几个地方需要手动触发调用查询接口:
- `componentDidMount()` 初始化
- `handleTableChange()` 分页/过滤/排序变化
- 点击搜索按钮触发的事件(官网没写)

我自己是没有用 componentDidUpdate 这种思路来实现过, 因为觉得可能需要判断的状态变化会比较多? 

这里引申到一个点是**什么时候该通过副作用(`useEffect`) 触发, 什么时候该通过事件触发**? 我理解通过副作用触发的好处是代码量会小很多. 但是存在的问题就是一旦 `useEffect` 依赖项写不对就可能出现多次渲染或者甚至触发无限渲染的问题.

举个例子一开始我做的时候是直接把 total 这个 pagination 参数包含到 query 里的. 然后请求接口里拿到返回数据后又会无脑再 set 一次(虽然 total 可能没变, 但是 query 这个对象地址变了)...这就直接导致触发无限渲染...

当然一般按照习惯 useEffect 里包含的副作用按照 eslint 提示写一般都是没问题的. 但是总归会需要有特殊情况考虑. 比如我看你的源码里也是使用 eslint-disabled 去注释掉提示的

比如官方的例子里 antd4 的 [远程加载数据](https://4x.ant.design/components/table/#components-table-demo-ajax) 使用的是 `JSON.stringify(tableParams)` 避免我上述 total 导致依赖对象地址变更造成的问题(所以需要加上 eslint disable...). 然后 antd5 又不把 total 放进去了, `useEffect` 的依赖变成了很单纯的 page 和 pageSize. 这种就没有问题了...只能说有时候官网可能自己也没有弄清楚最佳实践? 反正 4 的做法我不是很喜欢也挺误导人的...

然后就是另一种做法. 使用事件触发接口请求好处就是不会产生多余的副作用, 逻辑上会清晰很多. 想要什么时候请求就在需要的事件上请求就好了. 当然代码量也一定会增加很多...

以上均为自己的一点胡思乱想和讨论...再次感谢作者的整理

**Comment by acfasj** [comment]
@hacker0limbo 没想到会有人开issue hhhhh
我现在偶尔用 https://procomponents.ant.design/components/table , 没有去细看它是怎么实现的, 它是做了一套比较完整的业务上常见的封装的(就是文档很难读......

> 什么时候该通过副作用(useEffect) 触发, 什么时候该通过事件触发?

我同意能事件就事件, 也许可以看一下 useEffectEvent https://react.dev/learn/separating-events-from-effects#choosing-between-event-handlers-and-effects

感觉还是因为 react 拥抱 immutable 导致我们想这么多, 推荐一下 https://www.zhihu.com/question/632478500/answer/3340135201

**Comment by hacker0limbo** [comment]
@acfasj 感谢解答! pro components 我也确实用过. 文档是有点...

useEffectEvent 这个 hook 我看过, 但是这个应该还在试验阶段...可以观望下

最后推荐的文章很有趣. 感谢指点!
